### ISSUE TITLE
running errors

### ISSUE THREAD

**Issue by HongyuGong** [fuzhenxin/text_style_transfer#3]
Hi I running into errors when training the model, the running log is following:
******************************************************
Loading data
Building model
Building sampler
Building f_init... Done
Building f_next.. Done
Building f_init... Done
Building f_next.. Done
Building f_log_probs... Done
Building f_cost... Done
Computing gradient... Done
Traceback (most recent call last):
  File "train_nmt.py", line 55, in <module>
    'reload': [False]})
  File "train_nmt.py", line 42, in main
    style_adv=True)
  File "~/text_style_transfer/model/style_transfer/session_multi_decoder/nmt.py", line 1126, in train
    f_grad_shared0, f_update0 = eval(optimizer)(lr, tparams, grads0, inps1, cost0, cost_d, co
st_h, "0")
  File "~/text_style_transfer/model/style_transfer/session_multi_decoder/nmt.py", line 898, in adadelta
    profile=profile)
  File "~/.local/lib/python2.7/site-packages/theano/compile/function.py", line 317, in function
    output_keys=output_keys)
    File "~/.local/lib/python2.7/site-packages/theano/compile/pfunc.py", line 449, i
n pfunc
    no_default_updates=no_default_updates)
  File "~/.local/lib/python2.7/site-packages/theano/compile/pfunc.py", line 208, i
n rebuild_collect_shared
    raise TypeError(err_msg, err_sug)
TypeError: ('An update must have the same type as the original shared variable (shared_var=We
mb_encoder_rgrad2_0, shared_var.type=TensorType(float32, matrix), update_val=Elemwise{add,no_
inplace}.0, update_val.type=TensorType(float64, matrix)).', 'If the difference is related to 
the broadcast pattern, you can call the tensor.unbroadcast(var, axis_to_unbroadcast[, ...]) f
unction to remove broadcastable dimensions.')
******************************************************
Any ideas about the error?

**Comment by HongyuGong** [comment]
Solved by specifying THEANO_FLAGS='floatX=float32'
