### ISSUE TITLE
GpuArrayException: cuMemAlloc: CUDA_ERROR_OUT_OF_MEMORY: out of memory

### ISSUE THREAD

**Issue by zhunipingan** [fuzhenxin/text_style_transfer#7]
hi，
    when I run the train.sh on GPU, I met the following errors:
`Traceback (most recent call last):
  File "./train_nmt.py", line 55, in <module>
    'reload': [False]})
  File "./train_nmt.py", line 42, in main
    style_adv=True)
  File "model/style_transfer/session_multi_decoder/nmt.py", line 1176, in train
    cost, cost_d, cost_h = f_grad_shared[senti_index](x, x_mask, y, y_mask, senti)
  File "Theano/theano/compile/function_module.py", line 917, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "Theano/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "Theano/theano/compile/function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
  File "pygpu/gpuarray.pyx", line 700, in pygpu.gpuarray.pygpu_empty
  File "pygpu/gpuarray.pyx", line 301, in pygpu.gpuarray.array_empty
GpuArrayException: cuMemAlloc: CUDA_ERROR_OUT_OF_MEMORY: out of memory
` 
 The GPU memory is 12G, but I think may be it is enough, can you help me? thanks!

**Comment by fuzhenxin** [comment]
Hellos，
    Do you change the gpu id of the following line in train.sh:
```export THEANO_FLAGS=device=gpu3,floatX=float32,lib.cnmem=0.8```

**Comment by zhunipingan** [comment]
Thanks for your reply!
I noticed the code in train.sh,  I think if I use my gpu3, I needn't to do any modification.
But I still have the error, if you know some other reasons? Hhh, I can not solve it by myself now.
Thanks

**Comment by fuzhenxin** [comment]
Do you modify any code? I'm sure 12G is  enough. I did not meet the error ever.

**Comment by zhunipingan** [comment]
Thanks.
`Building f_init... Done
Building f_next.. Done
Building f_log_probs... Done
Building f_cost... Done
Computing gradient... Done
Building optimizers... Done
Optimization
Epoch  0 Update  100 style  1 Cost  71.04966 0.34096366 -0.34654176 UD  1.36920809746
Traceback (most recent call last):
  File "./train_nmt.py", line 55, in <module>
    'reload': [False]})
`
After the 0 epoch, it will say the gpu memeory error.  I will try to solve thisn problem. Thank you!

**Comment by zhunipingan** [comment]
maybe the batch size is too large, I just modify the batch size to 16, and it can be run now.
I have another question, if I want to run the model using another datasets, I think I just need to replace the q_train.txt q_val.txt q_test.txt,  r_train.txt r_val.txt r_test.tst,and s_train.txt s_val.txt s_test.tst with my own datasets. 
the q_*.txt is the same as r_*.txt, and the s_*.txt is the label of the corresponding q_*.txt. I want to know if my understanding is right, thanks~

**Comment by fuzhenxin** [comment]
Yeah, that is right!

**Comment by zhunipingan** [comment]
hi,
    I met the problem that after I ran the ./test.sh, I found the q_test_style_0.txt was empty and the q_test_style_0.txt was all dots such as '. . . . . . . . . . . . . . . '.
    I just modified the batch size in train_nmt.py from 128 to 16.
    Can you help me, thanks!!!

**Comment by fuzhenxin** [comment]
Which model and dataset do you use? I will try to reproduce the srror.

**Comment by zhunipingan** [comment]
hhh, thank you!
I use your origin dataset,  just as you wrote.
$ cd model/style_transfer/session_multi_decoder
$ ./train.sh   # train model
$ ./test.sh    # test model
$ ./com.sh     # show results in compare.txt
And to solve the problem of memory error, I modified the batch size in train_nmy.py to 16.

**Comment by fuzhenxin** [comment]
I met the same problen........ I am trying to fix it.

**Comment by zhunipingan** [comment]
hi,
   Have you found the solution.

**Comment by fuzhenxin** [comment]
I can not run it on gpu now due to nvidia cuda or driver error. I am running it on CPU slowly...

**Comment by fuzhenxin** [comment]
I do not find the solution now..

**Comment by fuzhenxin** [comment]
Can you add my wechat to talk about it conveniently 15650708568
